#!/usr/bin/env python3
"""Sequential evidence-assimilation screen for GRAM rule beliefs.

This is deliberately a *pre-active* screen.  Every controller receives the
same fixed public evidence sequence and never selects a probe:

``full six-frame support -> partial (1+3) -> neutral distractor -> strong``.

The experiment asks whether a belief can rapidly incorporate an observation,
retain its belief across an uninformative distractor, and recover the exact
rule after decisive evidence.  It compares an exact 64-code ceiling, the
trained fixed-K4 amortizer, raw GRAM prior samples, verifier-guided GRAM
population search (VPS), and a uniform-proposal VPS control.  A paired counterfactual branch
uses the same public states/actions but targets generated by another program
from the initial four-rule version space.

No result from this script establishes active experiment selection.  The
legacy RuleGrid candidate IDs and task IDs are never passed to a model.
Palette-role canonicalization, the factor axes, and the frozen executor remain
privileged diagnostic conveniences and are recorded as such in the artifact.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import hashlib
import json
import math
import os
from pathlib import Path
import random
import sys
import time
from typing import Any, Iterable, Sequence


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from prp_wm.rulegrid import MASTER_SEED


DEFAULT_EXECUTOR = REPOSITORY_ROOT / "runs/support_calibrated_executor_seed20260724/checkpoint_last.pt"
DEFAULT_GRAM = REPOSITORY_ROOT / "runs/gram_causal_screen600_fold0_seed20260728/checkpoint_last.pt"
DEFAULT_FIXED_K4 = REPOSITORY_ROOT / (
    "runs/factorization_latin_4fold_3seed_v1/runs/factorized-3x4/"
    "fold_0/seed_20260728/attempts/001/output/checkpoint_last.pt"
)
RESULT_SCHEMA_VERSION = "prp-wm.gram-vps-sequential-assimilation.v1"
_AUDITED_SOURCE_FILES = (
    "prp_wm/gram_smc.py",
    "prp_wm/gram_causal_rules.py",
    "prp_wm/discrete_causal_rules.py",
    "prp_wm/causal_rules.py",
    "prp_wm/causal_filter.py",
    "prp_wm/latent_rules.py",
    "prp_wm/neural.py",
    "prp_wm/pilot.py",
    "prp_wm/rulegrid.py",
    "scripts/run_gram_smc_active_screen.py",
    "scripts/run_gram_causal_screen.py",
    "scripts/run_expected_discrete_causal_coverage.py",
    "scripts/run_support_calibrated_executor.py",
)


@dataclass(frozen=True)
class EvidenceStep:
    """Evaluator-side probe selected before either target branch is built."""

    name: str
    candidate_index: int
    probe: Any


@dataclass(frozen=True)
class PairedEvidence:
    """Factual/counterfactual histories at t0..t3."""

    steps: tuple[tuple[EvidenceStep, ...], ...]
    factual_histories: tuple[tuple[tuple[Any, ...], ...], ...]
    counterfactual_histories: tuple[tuple[tuple[Any, ...], ...], ...]
    factual_programs: tuple[Any, ...]
    counterfactual_programs: tuple[Any, ...]


@dataclass(frozen=True)
class BeliefSnapshot:
    """Framework-independent weighted discrete belief for one task."""

    unique_codes: tuple[tuple[int, int, int], ...]
    unique_weights: tuple[float, ...]
    particle_codes: tuple[tuple[int, int, int], ...]
    particle_weights: tuple[float, ...]
    effective_sample_size: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--executor-checkpoint", type=Path, default=DEFAULT_EXECUTOR)
    parser.add_argument(
        "--active-verifier-checkpoint",
        type=Path,
        help=(
            "optional separately trained sequential verifier; the proposer keeps "
            "the original executor embedded in its checkpoint"
        ),
    )
    parser.add_argument("--gram-checkpoint", type=Path, default=DEFAULT_GRAM)
    parser.add_argument("--fixed-k4-checkpoint", type=Path, default=DEFAULT_FIXED_K4)
    parser.add_argument("--seed", type=int, default=20260729)
    parser.add_argument("--data-master-seed", type=int, default=MASTER_SEED)
    parser.add_argument("--eval-split", default="gram-vps-sequential-assimilation")
    parser.add_argument("--eval-tasks", type=int, default=12)
    parser.add_argument("--particles", type=int, default=32)
    parser.add_argument("--recursive-steps", type=int)
    parser.add_argument("--temperature", type=float, default=1.0)
    parser.add_argument("--ranking-inverse-temperature", type=float, default=1.0)
    parser.add_argument("--carry-limit", type=int)
    parser.add_argument("--proper-weight", type=float, default=1.0)
    parser.add_argument("--balanced-weight", type=float, default=0.0)
    parser.add_argument("--energy-scale", type=float)
    parser.add_argument(
        "--verifier-mode",
        choices=("learned", "symbolic"),
        default="learned",
        help=(
            "learned uses the frozen executor likelihood after a mandatory stage "
            "audit; symbolic is an explicitly privileged hard-consistency proposal ceiling"
        ),
    )
    parser.add_argument(
        "--allow-failed-verifier-audit",
        action="store_true",
        help="diagnostic only: continue learned population search after a failed MAP-exact gate",
    )
    parser.add_argument("--device", default="auto")
    return parser.parse_args()


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _source_sha256() -> dict[str, str]:
    return {
        relative: _sha256_file(REPOSITORY_ROOT / relative)
        for relative in _AUDITED_SOURCE_FILES
    }


def _atomic_json(path: Path, payload: dict[str, object]) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(
        json.dumps(payload, sort_keys=True, indent=2, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def _json_cli(args: argparse.Namespace) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in vars(args).items():
        if isinstance(value, Path):
            result[key] = str(value.resolve())
        elif isinstance(value, (tuple, list)):
            result[key] = list(value)
        else:
            result[key] = value
    return result


def _fresh_stage_seed(base_seed: int, stage_index: int) -> int:
    """Return the auditable fresh-proposal seed for one sequential stage."""

    if type(base_seed) is not int or type(stage_index) is not int or stage_index < 0:
        raise ValueError("base seed and non-negative stage index must be integers")
    return base_seed + stage_index


def _factor_code(program: Any) -> tuple[int, int, int]:
    from prp_wm.latent_rules import rule_program_factor_ids

    return rule_program_factor_ids(program)


def _select_fixed_evidence(task: Any) -> tuple[EvidenceStep, ...]:
    """Choose one partial, neutral, and strong probe evaluator-side.

    Candidate kind and probe ID never enter a model-facing tensor.  Selection
    is completed before either factual or counterfactual target is generated.
    """

    requested = (
        ("partial", "partial"),
        ("neutral", "neutral-large-change"),
        ("strong", "strong"),
    )
    steps: list[EvidenceStep] = []
    for public_name, private_kind in requested:
        try:
            index = task.privileged.candidate_kinds.index(private_kind)
        except ValueError as error:
            raise ValueError(f"task has no {private_kind!r} active candidate") from error
        steps.append(
            EvidenceStep(public_name, index, task.inference.active_candidates[index])
        )
    return tuple(steps)


def _counterfactual_program(
    task: Any,
    partial_probe: Any,
) -> Any:
    """Pick a support-compatible rule with a different partial outcome."""

    from prp_wm.rulegrid import simulate, version_space

    compatible = version_space(task.inference.support, task.privileged.palette)
    if len(compatible) != 4:
        raise AssertionError("full six-frame support must leave exactly four rules")
    true_program = task.privileged.true_program
    true_outcome = simulate(
        partial_probe.state,
        partial_probe.action,
        true_program,
        task.privileged.palette,
    )
    alternatives = tuple(
        program
        for program in compatible
        if program != true_program
        and simulate(
            partial_probe.state,
            partial_probe.action,
            program,
            task.privileged.palette,
        )
        != true_outcome
    )
    if not alternatives:
        raise AssertionError("the 1+3 partial probe needs a counterfactual outcome")
    return min(alternatives, key=lambda program: program.program_id)


def _build_paired_evidence(tasks: Sequence[Any]) -> PairedEvidence:
    """Build target-paired histories without changing public state/action inputs."""

    from prp_wm.rulegrid import RuleGridTransition, simulate, version_space

    materialized = tuple(tasks)
    if not materialized:
        raise ValueError("tasks cannot be empty")
    all_steps = tuple(_select_fixed_evidence(task) for task in materialized)
    factual_programs = tuple(task.privileged.true_program for task in materialized)
    counterfactual_programs = tuple(
        _counterfactual_program(task, steps[0].probe)
        for task, steps in zip(materialized, all_steps, strict=True)
    )

    factual_current = [list(task.inference.support) for task in materialized]
    counterfactual_current = [list(task.inference.support) for task in materialized]
    factual_stages: list[tuple[tuple[Any, ...], ...]] = [
        tuple(tuple(history) for history in factual_current)
    ]
    counterfactual_stages: list[tuple[tuple[Any, ...], ...]] = [
        tuple(tuple(history) for history in counterfactual_current)
    ]
    for step_index in range(3):
        for task_index, task in enumerate(materialized):
            probe = all_steps[task_index][step_index].probe
            factual_target = simulate(
                probe.state,
                probe.action,
                factual_programs[task_index],
                task.privileged.palette,
            )
            counterfactual_target = simulate(
                probe.state,
                probe.action,
                counterfactual_programs[task_index],
                task.privileged.palette,
            )
            factual_current[task_index].append(
                RuleGridTransition(probe.state, probe.action, factual_target)
            )
            counterfactual_current[task_index].append(
                RuleGridTransition(probe.state, probe.action, counterfactual_target)
            )
        factual_stages.append(tuple(tuple(history) for history in factual_current))
        counterfactual_stages.append(
            tuple(tuple(history) for history in counterfactual_current)
        )

    # Protocol invariants: partial branches differ, neutral adds no causal
    # information, and strong evidence leaves the selected rule exactly.
    for task_index, task in enumerate(materialized):
        factual_spaces = tuple(
            version_space(stage[task_index], task.privileged.palette)
            for stage in factual_stages
        )
        counterfactual_spaces = tuple(
            version_space(stage[task_index], task.privileged.palette)
            for stage in counterfactual_stages
        )
        for spaces, target_program in (
            (factual_spaces, factual_programs[task_index]),
            (counterfactual_spaces, counterfactual_programs[task_index]),
        ):
            if len(spaces[0]) != 4:
                raise AssertionError("t0 must have a four-rule version space")
            if len(spaces[1]) not in (1, 3):
                raise AssertionError("partial evidence must make a 1+3 partition")
            if spaces[2] != spaces[1]:
                raise AssertionError("neutral evidence must preserve the version space")
            if spaces[3] != (target_program,):
                raise AssertionError("strong evidence must identify the target rule")
        if factual_stages[1][task_index][-1].next_state == counterfactual_stages[1][task_index][-1].next_state:
            raise AssertionError("paired partial targets must differ")
        if factual_stages[2][task_index][-1].next_state != counterfactual_stages[2][task_index][-1].next_state:
            raise AssertionError("paired neutral targets must be equal")

    return PairedEvidence(
        steps=all_steps,
        factual_histories=tuple(factual_stages),
        counterfactual_histories=tuple(counterfactual_stages),
        factual_programs=factual_programs,
        counterfactual_programs=counterfactual_programs,
    )


def _support_batch(
    torch: Any,
    tasks: Sequence[Any],
    histories: Sequence[Sequence[Any]],
    *,
    device: Any,
) -> Any:
    """Tensorize arbitrary complete histories and canonicalize palette roles."""

    from prp_wm.latent_rules import canonicalize_rulegrid_tensor_batch
    from prp_wm.neural import RuleGridTensorBatch, encode_public_action

    materialized_tasks = tuple(tasks)
    materialized_histories = tuple(tuple(history) for history in histories)
    if not materialized_tasks or len(materialized_tasks) != len(materialized_histories):
        raise ValueError("tasks and histories must be non-empty and equally sized")
    lengths = {len(history) for history in materialized_histories}
    if len(lengths) != 1 or not next(iter(lengths)):
        raise ValueError("this fixed protocol requires equal non-empty histories")
    support_steps = next(iter(lengths))
    action_grid = [
        [encode_public_action(transition.action) for transition in history]
        for history in materialized_histories
    ]
    max_atoms = max(action.shape[0] for row in action_grid for action in row)
    padded_actions = torch.zeros(
        (len(materialized_tasks), support_steps, max_atoms, 4),
        dtype=torch.long,
        device=device,
    )
    action_mask = torch.zeros(
        (len(materialized_tasks), support_steps, max_atoms),
        dtype=torch.bool,
        device=device,
    )
    for task_index, row in enumerate(action_grid):
        for step_index, action in enumerate(row):
            atoms = action.shape[0]
            padded_actions[task_index, step_index, :atoms] = action.to(device)
            action_mask[task_index, step_index, :atoms] = True
    if max_atoms == 1:
        support_actions = padded_actions[:, :, 0]
        support_action_mask = None
    else:
        support_actions = padded_actions
        support_action_mask = action_mask
    raw = RuleGridTensorBatch(
        support_states=torch.tensor(
            [[transition.state for transition in history] for history in materialized_histories],
            dtype=torch.long,
            device=device,
        ),
        support_actions=support_actions,
        support_targets=torch.tensor(
            [[transition.next_state for transition in history] for history in materialized_histories],
            dtype=torch.long,
            device=device,
        ),
        support_mask=torch.ones(
            (len(materialized_tasks), support_steps),
            dtype=torch.bool,
            device=device,
        ),
        support_action_mask=support_action_mask,
    )
    return canonicalize_rulegrid_tensor_batch(raw, materialized_tasks)


def _normalised_weights(weights: Iterable[float]) -> tuple[float, ...]:
    materialized = tuple(float(weight) for weight in weights)
    total = sum(materialized)
    if not materialized or total <= 0 or any(weight < 0 for weight in materialized):
        raise ValueError("belief weights must be non-negative with positive mass")
    return tuple(weight / total for weight in materialized)


def _snapshot_from_particles(
    codes: Sequence[Sequence[int]],
    weights: Sequence[float] | None = None,
    *,
    unique_uniform: bool = False,
) -> BeliefSnapshot:
    """Aggregate duplicate factor tuples while retaining particle diagnostics."""

    particle_codes = tuple(tuple(int(value) for value in code) for code in codes)
    if not particle_codes or any(len(code) != 3 for code in particle_codes):
        raise ValueError("particle codes must be a non-empty sequence of triples")
    particle_weights = _normalised_weights(
        (1.0,) * len(particle_codes) if weights is None else weights
    )
    grouped: dict[tuple[int, int, int], float] = {}
    for code, weight in zip(particle_codes, particle_weights, strict=True):
        grouped[code] = grouped.get(code, 0.0) + weight
    grouped = {code: mass for code, mass in grouped.items() if mass > 0.0}
    if not grouped:
        raise ValueError("belief must retain at least one positive-mass code")
    if unique_uniform:
        uniform = 1.0 / len(grouped)
        grouped = {code: uniform for code in grouped}
        # Fixed K4 is explicitly interpreted as a uniform set of unique slots.
        ess = float(len(grouped))
    else:
        ess = 1.0 / sum(weight * weight for weight in particle_weights)
    ordered = sorted(grouped.items(), key=lambda item: (-item[1], item[0]))
    return BeliefSnapshot(
        unique_codes=tuple(code for code, _ in ordered),
        unique_weights=tuple(weight for _, weight in ordered),
        particle_codes=particle_codes,
        particle_weights=particle_weights,
        effective_sample_size=ess,
    )


def _snapshots_from_inference(inference: Any, *, unique_uniform: bool) -> tuple[BeliefSnapshot, ...]:
    rows = inference.factor_ids.detach().cpu().tolist()
    return tuple(
        _snapshot_from_particles(task_codes, unique_uniform=unique_uniform)
        for task_codes in rows
    )


def _snapshots_from_population(result: Any) -> tuple[BeliefSnapshot, ...]:
    population = result.population
    ids = population.factor_ids.detach().cpu()
    masks = population.mask.detach().cpu()
    weights = population.ranking_weights.detach().cpu()
    return tuple(
        _snapshot_from_particles(
            task_ids[task_mask].tolist(),
            task_weights[task_mask].tolist(),
        )
        for task_ids, task_mask, task_weights in zip(
            ids, masks, weights, strict=True
        )
    )


def _exact_snapshots(
    tasks: Sequence[Any],
    histories: Sequence[Sequence[Any]],
) -> tuple[BeliefSnapshot, ...]:
    from prp_wm.rulegrid import version_space

    return tuple(
        _snapshot_from_particles(
            [_factor_code(program) for program in version_space(history, task.privileged.palette)]
        )
        for task, history in zip(tasks, histories, strict=True)
    )


def _symbolic_population_stages(
    *,
    fresh_proposals_by_stage: Sequence[Sequence[BeliefSnapshot]],
    tasks: Sequence[Any],
    histories_by_stage: Sequence[Sequence[Sequence[Any]]],
    carry_limit: int,
) -> tuple[tuple[BeliefSnapshot, ...], ...]:
    """Exact-consistency population search over fresh plus carried codes.

    This mirrors the discrete population-search protocol without invoking a
    learned verifier: each stage merges exactly W fresh proposals with the
    preceding retained codes, deduplicates them, and keeps compatible codes.
    If none were proposed or carried, it retains the unfiltered candidates so
    ordinary metrics expose proposal failure; exact codes are never injected.
    """

    from prp_wm.rulegrid import version_space

    if carry_limit <= 0:
        raise ValueError("carry_limit must be positive")
    carried: list[tuple[tuple[int, int, int], ...]] = [tuple() for _ in tasks]
    stages: list[tuple[BeliefSnapshot, ...]] = []
    for fresh_stage, histories in zip(
        fresh_proposals_by_stage, histories_by_stage, strict=True
    ):
        retained_stage: list[BeliefSnapshot] = []
        for task_index, (fresh, task, history) in enumerate(
            zip(fresh_stage, tasks, histories, strict=True)
        ):
            ordered: list[tuple[int, int, int]] = []
            seen: set[tuple[int, int, int]] = set()
            for code in (*fresh.particle_codes, *carried[task_index]):
                if code not in seen:
                    seen.add(code)
                    ordered.append(code)
            compatible = {
                _factor_code(program)
                for program in version_space(history, task.privileged.palette)
            }
            exact = [code for code in ordered if code in compatible]
            selected = (exact if exact else ordered)[:carry_limit]
            if not selected:
                raise AssertionError("fresh proposal population cannot be empty")
            snapshot = _snapshot_from_particles(
                selected,
                unique_uniform=True,
            )
            carried[task_index] = snapshot.unique_codes
            retained_stage.append(snapshot)
        stages.append(tuple(retained_stage))
    return tuple(stages)


def _uniform_iid_proposal_stages(
    *,
    task_count: int,
    stages: int,
    proposals: int,
    seed: int,
) -> tuple[tuple[BeliefSnapshot, ...], ...]:
    """Matched fresh iid discrete proposal banks, independent of evidence."""

    if min(task_count, stages, proposals) <= 0:
        raise ValueError("task, stage, and proposal counts must be positive")
    return tuple(
        tuple(
            _snapshot_from_particles(
                [
                    (rng.randrange(4), rng.randrange(4), rng.randrange(4))
                    for _ in range(proposals)
                ]
            )
            for task_index in range(task_count)
            for rng in (
                random.Random(seed + 100_003 * task_index + 1_009 * stage_index),
            )
        )
        for stage_index in range(stages)
    )


def _verifier_branch_audit(
    *,
    torch: Any,
    executor: Any,
    tasks: Sequence[Any],
    batches: Sequence[Any],
    histories_by_stage: Sequence[Sequence[Sequence[Any]]],
    target_programs: Sequence[Any],
) -> tuple[dict[str, object], ...]:
    """Compare neural MAP-exact codes with the symbolic version space."""

    from prp_wm.causal_filter import score_hypothesis_bank
    from prp_wm.rulegrid import version_space

    records: list[dict[str, object]] = []
    executor.eval()
    with torch.no_grad():
        for batch, histories in zip(batches, histories_by_stage, strict=True):
            scores = score_hypothesis_bank(
                executor,
                batch.support_states,
                batch.support_actions,
                batch.support_targets,
                batch.support_mask,
                batch.support_action_mask,
            )
            bank = tuple(
                tuple(int(value) for value in row)
                for row in scores.factor_ids.detach().cpu().tolist()
            )
            map_exact = scores.map_exact.detach().cpu()
            true_exact = 0
            exact_set = 0
            any_exact = 0
            total_neural = 0
            precision = 0.0
            recall = 0.0
            for task_index, (task, history, target_program) in enumerate(
                zip(tasks, histories, target_programs, strict=True)
            ):
                symbolic = {
                    _factor_code(program)
                    for program in version_space(history, task.privileged.palette)
                }
                neural = {
                    code
                    for code, is_exact in zip(
                        bank, map_exact[task_index].tolist(), strict=True
                    )
                    if is_exact
                }
                overlap = neural.intersection(symbolic)
                target = _factor_code(target_program)
                true_exact += int(target in neural)
                exact_set += int(neural == symbolic)
                any_exact += int(bool(neural))
                total_neural += len(neural)
                precision += len(overlap) / len(neural) if neural else 0.0
                recall += len(overlap) / len(symbolic)
            count = len(tasks)
            records.append(
                {
                    "tasks": count,
                    "target_code_map_exact_rate": true_exact / count,
                    "any_neural_map_exact_code_task_rate": any_exact / count,
                    "neural_map_exact_set_matches_symbolic_rate": exact_set / count,
                    "mean_neural_map_exact_codes": total_neural / count,
                    "mean_neural_map_exact_precision": precision / count,
                    "mean_neural_map_exact_recall": recall / count,
                }
            )
    return tuple(records)


def _verifier_stage_audit(
    *,
    torch: Any,
    executor: Any,
    tasks: Sequence[Any],
    paired: PairedEvidence,
    factual_batches: Sequence[Any],
    counterfactual_batches: Sequence[Any],
) -> dict[str, object]:
    stage_names = ("t0_support", "t1_partial", "t2_neutral", "t3_strong")
    factual = _verifier_branch_audit(
        torch=torch,
        executor=executor,
        tasks=tasks,
        batches=factual_batches,
        histories_by_stage=paired.factual_histories,
        target_programs=paired.factual_programs,
    )
    counterfactual = _verifier_branch_audit(
        torch=torch,
        executor=executor,
        tasks=tasks,
        batches=counterfactual_batches,
        histories_by_stage=paired.counterfactual_histories,
        target_programs=paired.counterfactual_programs,
    )
    stages = [
        {
            "stage": name,
            "factual": factual[index],
            "counterfactual": counterfactual[index],
        }
        for index, name in enumerate(stage_names)
    ]
    passed = all(
        branch["target_code_map_exact_rate"] == 1.0
        and branch["neural_map_exact_set_matches_symbolic_rate"] == 1.0
        for record in stages
        for branch in (record["factual"], record["counterfactual"])
    )
    return {
        "gate_definition": (
            "for every stage and branch, the target code must be neural-MAP exact "
            "and the neural MAP-exact bank must equal the symbolic version space"
        ),
        "passed": passed,
        "stages": stages,
    }


def _entropy_bits(weights: Iterable[float]) -> float:
    return -sum(weight * math.log2(weight) for weight in weights if weight > 0)


def _js_divergence_bits(left: BeliefSnapshot, right: BeliefSnapshot) -> float:
    left_mass = dict(zip(left.unique_codes, left.unique_weights, strict=True))
    right_mass = dict(zip(right.unique_codes, right.unique_weights, strict=True))
    codes = set(left_mass).union(right_mass)
    divergence = 0.0
    for code in codes:
        p = left_mass.get(code, 0.0)
        q = right_mass.get(code, 0.0)
        midpoint = 0.5 * (p + q)
        if p > 0:
            divergence += 0.5 * p * math.log2(p / midpoint)
        if q > 0:
            divergence += 0.5 * q * math.log2(q / midpoint)
    return divergence


def _aggregate_snapshot_metrics(
    snapshots: Sequence[BeliefSnapshot],
    tasks: Sequence[Any],
    histories: Sequence[Sequence[Any]],
    target_programs: Sequence[Any],
) -> dict[str, object]:
    from prp_wm.rulegrid import version_space

    totals = {
        "target_covered": 0.0,
        "target_mass": 0.0,
        "top1_target": 0.0,
        "compatible_mass": 0.0,
        "compatible_precision": 0.0,
        "compatible_recall": 0.0,
        "exact_set": 0.0,
        "valid_particle_rate": 0.0,
        "unique": 0.0,
        "ess": 0.0,
        "entropy": 0.0,
    }
    version_sizes: dict[str, int] = {}
    target_ranks: list[int] = []
    for snapshot, task, history, target_program in zip(
        snapshots, tasks, histories, target_programs, strict=True
    ):
        compatible = {
            _factor_code(program)
            for program in version_space(history, task.privileged.palette)
        }
        if not compatible:
            raise AssertionError("fixed evidence protocol produced an empty version space")
        target = _factor_code(target_program)
        unique = set(snapshot.unique_codes)
        overlap = unique.intersection(compatible)
        mass = dict(zip(snapshot.unique_codes, snapshot.unique_weights, strict=True))
        target_mass = mass.get(target, 0.0)
        totals["target_covered"] += float(target in unique)
        totals["target_mass"] += target_mass
        totals["top1_target"] += float(snapshot.unique_codes[0] == target)
        totals["compatible_mass"] += sum(mass.get(code, 0.0) for code in compatible)
        totals["compatible_precision"] += len(overlap) / len(unique)
        totals["compatible_recall"] += len(overlap) / len(compatible)
        totals["exact_set"] += float(unique == compatible)
        totals["valid_particle_rate"] += sum(
            code in compatible for code in snapshot.particle_codes
        ) / len(snapshot.particle_codes)
        totals["unique"] += len(unique)
        totals["ess"] += snapshot.effective_sample_size
        totals["entropy"] += _entropy_bits(snapshot.unique_weights)
        version_sizes[str(len(compatible))] = version_sizes.get(str(len(compatible)), 0) + 1
        if target in snapshot.unique_codes:
            target_ranks.append(snapshot.unique_codes.index(target) + 1)
    count = len(snapshots)
    return {
        "tasks": count,
        "exact_version_space_size_histogram": version_sizes,
        "target_code_in_belief_rate": totals["target_covered"] / count,
        "mean_target_code_weight": totals["target_mass"] / count,
        "top1_target_code_rate": totals["top1_target"] / count,
        "mean_target_rank_when_covered": (
            sum(target_ranks) / len(target_ranks) if target_ranks else None
        ),
        "mean_compatible_weight": totals["compatible_mass"] / count,
        "mean_invalid_weight": 1.0 - totals["compatible_mass"] / count,
        "mean_unique_compatible_precision": totals["compatible_precision"] / count,
        "mean_exact_version_space_recall": totals["compatible_recall"] / count,
        "exact_version_space_set_recovery_rate": totals["exact_set"] / count,
        "valid_particle_rate": totals["valid_particle_rate"] / count,
        "mean_unique_codes": totals["unique"] / count,
        "mean_weight_effective_support_size": totals["ess"] / count,
        "mean_belief_entropy_bits": totals["entropy"] / count,
    }


def _conditional_recovery_metrics(
    before: Sequence[BeliefSnapshot],
    after: Sequence[BeliefSnapshot],
    target_codes: Sequence[tuple[int, int, int]],
) -> dict[str, object]:
    """Count recovery after decisive evidence with explicit denominators."""

    if not (len(before) == len(after) == len(target_codes)):
        raise ValueError("before, after, and target codes must have equal lengths")
    missing_denominator = 0
    missing_recovered = 0
    wrong_top1_denominator = 0
    wrong_top1_recovered = 0
    for previous, current, target in zip(
        before, after, target_codes, strict=True
    ):
        if target not in previous.unique_codes:
            missing_denominator += 1
            missing_recovered += int(target in current.unique_codes)
        if previous.unique_codes[0] != target:
            wrong_top1_denominator += 1
            wrong_top1_recovered += int(current.unique_codes[0] == target)
    return {
        "target_missing_at_t2_tasks": missing_denominator,
        "target_recovered_in_bank_at_t3_tasks": missing_recovered,
        "p_target_in_bank_t3_given_missing_t2": (
            missing_recovered / missing_denominator
            if missing_denominator
            else None
        ),
        "top1_wrong_at_t2_tasks": wrong_top1_denominator,
        "top1_corrected_at_t3_tasks": wrong_top1_recovered,
        "p_top1_target_t3_given_wrong_t2": (
            wrong_top1_recovered / wrong_top1_denominator
            if wrong_top1_denominator
            else None
        ),
    }


def _method_report(
    *,
    tasks: Sequence[Any],
    paired: PairedEvidence,
    factual: Sequence[Sequence[BeliefSnapshot]],
    counterfactual: Sequence[Sequence[BeliefSnapshot]],
    diagnostics: Sequence[dict[str, object]] | None = None,
) -> dict[str, object]:
    stage_names = ("t0_support", "t1_partial", "t2_neutral", "t3_strong")
    if len(factual) != 4 or len(counterfactual) != 4:
        raise ValueError("the fixed assimilation protocol has exactly four stages")
    stages: list[dict[str, object]] = []
    for stage_index, name in enumerate(stage_names):
        factual_metrics = _aggregate_snapshot_metrics(
            factual[stage_index],
            tasks,
            paired.factual_histories[stage_index],
            paired.factual_programs,
        )
        counterfactual_metrics = _aggregate_snapshot_metrics(
            counterfactual[stage_index],
            tasks,
            paired.counterfactual_histories[stage_index],
            paired.counterfactual_programs,
        )
        paired_jsd = sum(
            _js_divergence_bits(left, right)
            for left, right in zip(
                factual[stage_index], counterfactual[stage_index], strict=True
            )
        ) / len(tasks)
        record: dict[str, object] = {
            "stage": name,
            "observed_transitions": len(paired.factual_histories[stage_index][0]),
            "factual": factual_metrics,
            "counterfactual": counterfactual_metrics,
            "mean_factual_counterfactual_jsd_bits": paired_jsd,
        }
        if diagnostics is not None:
            record["filter_diagnostics"] = diagnostics[stage_index]
        stages.append(record)

    def mean_adjacent_jsd(branch: Sequence[Sequence[BeliefSnapshot]], left: int, right: int) -> float:
        return sum(
            _js_divergence_bits(before, after)
            for before, after in zip(branch[left], branch[right], strict=True)
        ) / len(tasks)

    def conditional_strong_recovery(
        branch: Sequence[Sequence[BeliefSnapshot]],
        target_programs: Sequence[Any],
    ) -> dict[str, object]:
        return _conditional_recovery_metrics(
            branch[2],
            branch[3],
            tuple(_factor_code(program) for program in target_programs),
        )

    def coverage_drop_count(
        branch: Sequence[Sequence[BeliefSnapshot]],
        target_programs: Sequence[Any],
    ) -> int:
        return sum(
            _factor_code(target_program) in before.unique_codes
            and _factor_code(target_program) not in after.unique_codes
            for before, after, target_program in zip(
                branch[1], branch[2], target_programs, strict=True
            )
        )

    return {
        "stages": stages,
        "neutral_distractor_stability": {
            "factual_mean_jsd_t1_to_t2_bits": mean_adjacent_jsd(factual, 1, 2),
            "counterfactual_mean_jsd_t1_to_t2_bits": mean_adjacent_jsd(counterfactual, 1, 2),
            "factual_target_coverage_drop_tasks_t1_to_t2": coverage_drop_count(
                factual, paired.factual_programs
            ),
            "counterfactual_target_coverage_drop_tasks_t1_to_t2": coverage_drop_count(
                counterfactual, paired.counterfactual_programs
            ),
        },
        "strong_evidence_recovery": {
            "factual_target_coverage_gain_t3_minus_t2": (
                stages[3]["factual"]["target_code_in_belief_rate"]
                - stages[2]["factual"]["target_code_in_belief_rate"]
            ),
            "factual_target_weight_gain_t3_minus_t2": (
                stages[3]["factual"]["mean_target_code_weight"]
                - stages[2]["factual"]["mean_target_code_weight"]
            ),
            "counterfactual_target_coverage_gain_t3_minus_t2": (
                stages[3]["counterfactual"]["target_code_in_belief_rate"]
                - stages[2]["counterfactual"]["target_code_in_belief_rate"]
            ),
            "counterfactual_target_weight_gain_t3_minus_t2": (
                stages[3]["counterfactual"]["mean_target_code_weight"]
                - stages[2]["counterfactual"]["mean_target_code_weight"]
            ),
            "factual_conditional": conditional_strong_recovery(
                factual, paired.factual_programs
            ),
            "counterfactual_conditional": conditional_strong_recovery(
                counterfactual, paired.counterfactual_programs
            ),
        },
    }


def _population_stage_diagnostics(
    torch: Any,
    result: Any,
    ranking_inverse_temperature: float,
) -> dict[str, object]:
    scales = result.applied_energy_scales.detach().cpu()
    population = result.population
    proposed = result.proposed_factor_ids.detach().cpu()
    mean_proposed_unique = sum(
        int(torch.unique(row, dim=0).shape[0]) for row in proposed
    ) / proposed.shape[0]
    valid_candidates = result.candidate_mask
    carried_candidates = result.candidate_was_carried & valid_candidates
    retained_exact = population.map_exact[population.mask]
    return {
        "ranking_inverse_temperature": ranking_inverse_temperature,
        "ranking_weights_are_posterior_mass": False,
        "mean_applied_energy_scale": float(scales.mean()),
        "mean_ranking_temperature_times_energy_scale": float(
            (scales * ranking_inverse_temperature).mean()
        ),
        "fresh_proposals_per_task": int(proposed.shape[1]),
        "mean_fresh_proposal_unique_codes": mean_proposed_unique,
        "mean_deduplicated_candidate_codes": float(
            valid_candidates.sum(dim=1).float().mean().cpu()
        ),
        "mean_retained_population_codes": float(
            population.counts.float().mean().cpu()
        ),
        "retained_map_exact_code_rate": (
            float(retained_exact.float().mean().cpu())
            if retained_exact.numel()
            else 0.0
        ),
        "candidate_carried_code_rate": float(
            carried_candidates.sum().float().cpu()
            / valid_candidates.sum().clamp_min(1).float().cpu()
        ),
        "population_generation": population.generation,
        "verifier_bank_evaluations": result.verifier_bank_evaluations,
    }


def _load_models(
    torch: Any,
    args: argparse.Namespace,
    device: Any,
) -> tuple[Any, Any, Any, Any, dict[str, Any]]:
    from prp_wm.discrete_causal_rules import ExpectedDiscreteCausalK4
    from prp_wm.gram_causal_rules import GRAMFactorizedCausalK4
    from scripts.run_causal_mechanism_coverage import _load_executor
    from scripts.run_expected_discrete_causal_coverage import _load_audited_executor

    executor_path = args.executor_checkpoint.resolve()
    active_verifier_path = (
        executor_path
        if args.active_verifier_checkpoint is None
        else args.active_verifier_checkpoint.resolve()
    )
    executor, executor_metadata = _load_audited_executor(torch, executor_path, device)

    fixed_checkpoint = torch.load(
        args.fixed_k4_checkpoint.resolve(), map_location="cpu", weights_only=False
    )
    if fixed_checkpoint.get("checkpoint_schema_version") != "prp-wm.expected-discrete-causal-k4.v1":
        raise SystemExit("unexpected fixed-K4 checkpoint schema")
    fixed = ExpectedDiscreteCausalK4(
        executor,
        attention_layers=int(fixed_checkpoint.get("attention_layers", 2)),
        temperature=float(fixed_checkpoint.get("factor_temperature_end", args.temperature)),
    ).to(device)
    fixed.load_state_dict(fixed_checkpoint["model_state_dict"], strict=True)
    fixed.eval()

    gram_checkpoint = torch.load(
        args.gram_checkpoint.resolve(), map_location="cpu", weights_only=False
    )
    if gram_checkpoint.get("checkpoint_schema_version") != "prp-wm.gram-factorized-causal-k4.v1":
        raise SystemExit("unexpected GRAM checkpoint schema")
    cli = gram_checkpoint.get("cli_arguments", {})
    bounds = gram_checkpoint.get("guidance_log_variance_bounds", (-8.0, 4.0))
    gram = GRAMFactorizedCausalK4(
        executor,
        recursive_steps=int(gram_checkpoint["recursive_steps"]),
        guidance_dim=int(gram_checkpoint["guidance_dim"]),
        attention_layers=int(cli.get("attention_layers", 2)),
        temperature=float(cli.get("factor_temperature_end", args.temperature)),
        minimum_log_variance=float(bounds[0]),
        maximum_log_variance=float(bounds[1]),
        initial_log_variance=float(gram_checkpoint.get("initial_guidance_log_variance", -2.0)),
        truncate_between_steps=bool(
            gram_checkpoint.get("truncate_between_recursive_steps", True)
        ),
    ).to(device)
    gram.load_state_dict(gram_checkpoint["model_state_dict"], strict=True)
    gram.eval()
    active_verifier = executor
    active_verifier_metadata = executor_metadata
    if args.active_verifier_checkpoint is not None:
        active_verifier, active_verifier_metadata = _load_executor(
            torch,
            args.active_verifier_checkpoint.resolve(),
            device,
        )
        active_verifier.eval()
        if active_verifier.config != gram.executor.config:
            raise SystemExit("active verifier and proposer executor configs differ")
    metadata = {
        "executor_checkpoint": executor_metadata,
        "active_verifier_checkpoint": active_verifier_metadata,
        "fixed_checkpoint": fixed_checkpoint,
        "gram_checkpoint": gram_checkpoint,
    }
    return executor, active_verifier, fixed, gram, metadata


def _validate_args(args: argparse.Namespace) -> None:
    for name in ("eval_tasks", "particles"):
        if getattr(args, name) <= 0:
            raise SystemExit(f"--{name.replace('_', '-')} must be positive")
    if args.recursive_steps is not None and args.recursive_steps <= 0:
        raise SystemExit("--recursive-steps must be positive")
    if args.temperature <= 0:
        raise SystemExit("--temperature must be positive")
    if args.ranking_inverse_temperature < 0:
        raise SystemExit("--ranking-inverse-temperature cannot be negative")
    if args.carry_limit is not None and args.carry_limit <= 0:
        raise SystemExit("--carry-limit must be positive")
    for name in (
        "proper_weight",
        "balanced_weight",
    ):
        if getattr(args, name) < 0:
            raise SystemExit(f"--{name.replace('_', '-')} cannot be negative")
    if args.energy_scale is not None and args.energy_scale <= 0:
        raise SystemExit("--energy-scale must be positive")


def main() -> None:
    args = parse_args()
    _validate_args(args)
    os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":4096:8")
    import torch

    from prp_wm.gram_smc import GRAMVerifierPopulationSearch
    from prp_wm.pilot import make_pilot_tasks
    from prp_wm.rulegrid import version_space
    from scripts.run_causal_mechanism_coverage import (
        _configure_determinism,
        _resolve_device,
    )
    from scripts.run_expected_discrete_causal_coverage import _build_context_pool

    device = _resolve_device(torch, args.device)
    _configure_determinism(torch, args.seed)
    proposer_executor, active_verifier, fixed, gram, checkpoints = _load_models(
        torch, args, device
    )
    if proposer_executor is not gram.executor:
        raise AssertionError("the GRAM proposal must retain its original executor")
    gram_fold = checkpoints["gram_checkpoint"].get("context_fold")
    fixed_fold = checkpoints["fixed_checkpoint"].get("context_fold")
    gram_seed = checkpoints["gram_checkpoint"].get("model_seed")
    fixed_seed = checkpoints["fixed_checkpoint"].get("model_seed")
    if gram_fold is None or gram_fold != fixed_fold:
        raise SystemExit("GRAM and fixed-K4 checkpoints must share a Latin context fold")
    if gram_seed != fixed_seed:
        raise SystemExit("GRAM and fixed-K4 checkpoints must share a model seed")
    tasks = _build_context_pool(
        make_pilot_tasks=make_pilot_tasks,
        split=args.eval_split,
        master_seed=args.data_master_seed,
        diagnostic_indices=(0,),
        count=args.eval_tasks,
        heldout=True,
        factor_ids_for_program=_factor_code,
        version_space=version_space,
        context_fold=int(gram_fold),
    )
    paired = _build_paired_evidence(tasks)
    factual_batches = tuple(
        _support_batch(torch, tasks, histories, device=device)
        for histories in paired.factual_histories
    )
    counterfactual_batches = tuple(
        _support_batch(torch, tasks, histories, device=device)
        for histories in paired.counterfactual_histories
    )
    recursive_steps = (
        gram.recursive_steps if args.recursive_steps is None else args.recursive_steps
    )

    verifier_audit = _verifier_stage_audit(
        torch=torch,
        executor=active_verifier,
        tasks=tasks,
        paired=paired,
        factual_batches=factual_batches,
        counterfactual_batches=counterfactual_batches,
    )
    if (
        args.verifier_mode == "learned"
        and not verifier_audit["passed"]
        and not args.allow_failed_verifier_audit
    ):
        output = args.output.resolve()
        output.mkdir(parents=True, exist_ok=True)
        active_path = (
            args.executor_checkpoint.resolve()
            if args.active_verifier_checkpoint is None
            else args.active_verifier_checkpoint.resolve()
        )
        audit_only: dict[str, object] = {
            "result_schema_version": RESULT_SCHEMA_VERSION,
            "experiment": "gram_vps_sequential_evidence_assimilation_screen",
            "status": "verifier_stage_audit_failed",
            "population_search_executed": False,
            "reason": (
                "The learned verifier failed the required sequential MAP-exact "
                "gate; population ranking would not be interpretable. Pass an "
                "active-calibrated verifier or select --verifier-mode symbolic."
            ),
            "cli_arguments": _json_cli(args),
            "context_fold": gram_fold,
            "tasks": len(tasks),
            "verifier_stage_audit": verifier_audit,
            "active_verifier": {
                "path": str(active_path),
                "sha256": _sha256_file(active_path),
                "same_object_as_proposer_executor": active_verifier is proposer_executor,
            },
            "source_sha256": _source_sha256(),
        }
        _atomic_json(output / "result.json", audit_only)
        print(json.dumps(audit_only, sort_keys=True, indent=2, allow_nan=False))
        return

    methods: dict[str, object] = {}
    started = time.perf_counter()
    exact_factual = tuple(
        _exact_snapshots(tasks, histories) for histories in paired.factual_histories
    )
    exact_counterfactual = tuple(
        _exact_snapshots(tasks, histories)
        for histories in paired.counterfactual_histories
    )
    methods["exact_64_state_filter"] = {
        "kind": "privileged_exact_ceiling",
        "weight_semantics": "uniform probability over exact symbolic version space",
        **_method_report(
            tasks=tasks,
            paired=paired,
            factual=exact_factual,
            counterfactual=exact_counterfactual,
        ),
    }

    with torch.no_grad():
        fixed_factual = tuple(
            _snapshots_from_inference(
                fixed.infer_support(batch, temperature=args.temperature),
                unique_uniform=True,
            )
            for batch in factual_batches
        )
        fixed_counterfactual = tuple(
            _snapshots_from_inference(
                fixed.infer_support(batch, temperature=args.temperature),
                unique_uniform=True,
            )
            for batch in counterfactual_batches
        )
    methods["fixed_k4_reinfer"] = {
        "kind": "deterministic_amortized_unique_uniform",
        "weight_semantics": "uniform over unique deterministic K4 slot codes",
        "particles": 4,
        **_method_report(
            tasks=tasks,
            paired=paired,
            factual=fixed_factual,
            counterfactual=fixed_counterfactual,
        ),
    }

    raw_factual: list[tuple[BeliefSnapshot, ...]] = []
    raw_counterfactual: list[tuple[BeliefSnapshot, ...]] = []
    with torch.no_grad():
        for stage, (factual_batch, counterfactual_batch) in enumerate(
            zip(factual_batches, counterfactual_batches, strict=True)
        ):
            # Common random numbers across t0..t3 isolate evidence response
            # from ordinary Monte-Carlo sample churn.
            seed = args.seed + 10_000
            factual_inference = gram.sample_width_candidates(
                factual_batch,
                width=args.particles,
                recursive_steps=recursive_steps,
                seed=seed,
                temperature=args.temperature,
                sample_noise=True,
            )
            counterfactual_inference = gram.sample_width_candidates(
                counterfactual_batch,
                width=args.particles,
                recursive_steps=recursive_steps,
                seed=seed,
                temperature=args.temperature,
                sample_noise=True,
            )
            raw_factual.append(
                _snapshots_from_inference(factual_inference, unique_uniform=False)
            )
            raw_counterfactual.append(
                _snapshots_from_inference(
                    counterfactual_inference, unique_uniform=False
                )
            )
    methods["raw_gram_prior_reinfer"] = {
        "kind": "support_conditioned_iid_prior_trajectories",
        "weight_semantics": "empirical frequency among iid final prior trajectories",
        "particles": args.particles,
        "recursive_steps": recursive_steps,
        "common_random_numbers_across_stages": True,
        "neutral_jsd_interpretation": "evidence response with sampling noise held fixed",
        **_method_report(
            tasks=tasks,
            paired=paired,
            factual=raw_factual,
            counterfactual=raw_counterfactual,
        ),
    }

    for proposal_mode in (
        ("gram", "uniform") if args.verifier_mode == "learned" else ()
    ):
        search = GRAMVerifierPopulationSearch(
            gram,
            verifier_executor=active_verifier,
            proposals=args.particles,
            recursive_steps=recursive_steps,
            proposal_mode=proposal_mode,
            carry_limit=args.carry_limit,
            ranking_inverse_temperature=args.ranking_inverse_temperature,
            proper_weight=args.proper_weight,
            balanced_weight=args.balanced_weight,
            energy_scale=args.energy_scale,
        ).eval()
        factual_stages: list[tuple[BeliefSnapshot, ...]] = []
        counterfactual_stages: list[tuple[BeliefSnapshot, ...]] = []
        diagnostics: list[dict[str, object]] = []
        factual_population = None
        counterfactual_population = None
        for stage, (factual_batch, counterfactual_batch) in enumerate(
            zip(factual_batches, counterfactual_batches, strict=True)
        ):
            # Population search intentionally draws a fresh W proposals at
            # every stage; neutral drift therefore includes search churn.
            seed = _fresh_stage_seed(args.seed + 100_000, stage)
            factual_result = search.search(
                factual_batch,
                carried=factual_population,
                seed=seed,
                temperature=args.temperature,
            )
            counterfactual_result = search.search(
                counterfactual_batch,
                carried=counterfactual_population,
                seed=seed,
                temperature=args.temperature,
            )
            factual_population = factual_result.population
            counterfactual_population = counterfactual_result.population
            factual_stages.append(_snapshots_from_population(factual_result))
            counterfactual_stages.append(
                _snapshots_from_population(counterfactual_result)
            )
            diagnostics.append(
                {
                    "factual": _population_stage_diagnostics(
                        torch,
                        factual_result,
                        args.ranking_inverse_temperature,
                    ),
                    "counterfactual": _population_stage_diagnostics(
                        torch,
                        counterfactual_result,
                        args.ranking_inverse_temperature,
                    ),
                }
            )
        method_name = f"{proposal_mode}_verifier_population_search"
        methods[method_name] = {
            "kind": (
                "learned_gram_proposal_verifier_guided_population_search"
                if proposal_mode == "gram"
                else "uniform_iid_proposal_verifier_guided_population_control"
            ),
            "proposal_mode": proposal_mode,
            "fresh_proposals_per_stage": args.particles,
            "recursive_steps_per_gram_proposal": recursive_steps,
            "carry_limit": search.carry_limit,
            "ranking_inverse_temperature": args.ranking_inverse_temperature,
            "ranking_weights_are_posterior_mass": False,
            "weight_semantics": "one-shot normalized verifier energy ranking only",
            "complete_history_rescored_once_per_stage": True,
            "path_weights_accumulated": False,
            "neutral_jsd_interpretation": "evidence response plus fresh-proposal/carry churn",
            "proper_weight": args.proper_weight,
            "balanced_weight": args.balanced_weight,
            "energy_scale_override": args.energy_scale,
            **_method_report(
                tasks=tasks,
                paired=paired,
                factual=factual_stages,
                counterfactual=counterfactual_stages,
                diagnostics=diagnostics,
            ),
        }

    if args.verifier_mode == "symbolic":
        symbolic_carry_limit = args.particles if args.carry_limit is None else args.carry_limit
        symbolic_gram_factual: list[tuple[BeliefSnapshot, ...]] = []
        symbolic_gram_counterfactual: list[tuple[BeliefSnapshot, ...]] = []
        with torch.no_grad():
            for stage, (factual_batch, counterfactual_batch) in enumerate(
                zip(factual_batches, counterfactual_batches, strict=True)
            ):
                stage_seed = _fresh_stage_seed(args.seed + 300_000, stage)
                factual_inference = gram.sample_width_candidates(
                    factual_batch,
                    width=args.particles,
                    recursive_steps=recursive_steps,
                    seed=stage_seed,
                    temperature=args.temperature,
                    sample_noise=True,
                )
                counterfactual_inference = gram.sample_width_candidates(
                    counterfactual_batch,
                    width=args.particles,
                    recursive_steps=recursive_steps,
                    seed=stage_seed,
                    temperature=args.temperature,
                    sample_noise=True,
                )
                symbolic_gram_factual.append(
                    _snapshots_from_inference(
                        factual_inference, unique_uniform=False
                    )
                )
                symbolic_gram_counterfactual.append(
                    _snapshots_from_inference(
                        counterfactual_inference, unique_uniform=False
                    )
                )
        gram_symbolic_factual = _symbolic_population_stages(
            fresh_proposals_by_stage=symbolic_gram_factual,
            tasks=tasks,
            histories_by_stage=paired.factual_histories,
            carry_limit=symbolic_carry_limit,
        )
        gram_symbolic_counterfactual = _symbolic_population_stages(
            fresh_proposals_by_stage=symbolic_gram_counterfactual,
            tasks=tasks,
            histories_by_stage=paired.counterfactual_histories,
            carry_limit=symbolic_carry_limit,
        )
        methods["gram_symbolic_population_search_ceiling"] = {
            "kind": "privileged_symbolic_population_search_over_gram_proposals",
            "weight_semantics": (
                "uniform over retained compatible codes; if none were proposed, "
                "uniform over retained unfiltered failure candidates"
            ),
            "proposal_mode": "gram",
            "fresh_proposals_per_stage": args.particles,
            "recursive_steps_per_gram_proposal": recursive_steps,
            "carry_limit": symbolic_carry_limit,
            "no_exact_bank_fallback": True,
            "persistent_discrete_population": True,
            "path_weights_accumulated": False,
            "fresh_random_seed_per_stage": True,
            "neutral_jsd_interpretation": (
                "evidence response plus fresh-proposal/carry churn under unchanged "
                "symbolic version space"
            ),
            **_method_report(
                tasks=tasks,
                paired=paired,
                factual=gram_symbolic_factual,
                counterfactual=gram_symbolic_counterfactual,
            ),
        }
        uniform_proposals = _uniform_iid_proposal_stages(
            task_count=len(tasks),
            stages=4,
            proposals=args.particles,
            seed=args.seed + 500_000,
        )
        uniform_factual = _symbolic_population_stages(
            fresh_proposals_by_stage=uniform_proposals,
            tasks=tasks,
            histories_by_stage=paired.factual_histories,
            carry_limit=symbolic_carry_limit,
        )
        uniform_counterfactual = _symbolic_population_stages(
            fresh_proposals_by_stage=uniform_proposals,
            tasks=tasks,
            histories_by_stage=paired.counterfactual_histories,
            carry_limit=symbolic_carry_limit,
        )
        methods["uniform_symbolic_population_search_ceiling"] = {
            "kind": "privileged_symbolic_population_search_uniform_iid_control",
            "weight_semantics": (
                "uniform over retained compatible codes; if none were proposed, "
                "uniform over retained unfiltered failure candidates"
            ),
            "proposal_mode": "uniform",
            "fresh_proposals_per_stage": args.particles,
            "carry_limit": symbolic_carry_limit,
            "no_exact_bank_fallback": True,
            "persistent_discrete_population": True,
            "path_weights_accumulated": False,
            "fresh_random_seed_per_stage": True,
            "neutral_jsd_interpretation": "fresh-proposal/carry churn under unchanged symbolic version space",
            **_method_report(
                tasks=tasks,
                paired=paired,
                factual=uniform_factual,
                counterfactual=uniform_counterfactual,
            ),
        }

    elapsed = time.perf_counter() - started
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    result_path = output / "result.json"
    executor_path = args.executor_checkpoint.resolve()
    active_verifier_path = (
        executor_path
        if args.active_verifier_checkpoint is None
        else args.active_verifier_checkpoint.resolve()
    )
    gram_path = args.gram_checkpoint.resolve()
    fixed_path = args.fixed_k4_checkpoint.resolve()
    result: dict[str, object] = {
        "result_schema_version": RESULT_SCHEMA_VERSION,
        "experiment": "gram_vps_sequential_evidence_assimilation_screen",
        "result_kind": "pre_active_fixed_probe_falsification_screen",
        "cli_arguments": _json_cli(args),
        "protocol": {
            "stage_names": ["t0_support", "t1_partial", "t2_neutral", "t3_strong"],
            "initial_support_transitions": 6,
            "fixed_evidence_sequence": ["partial_1_plus_3", "neutral_distractor", "strong_1_plus_1_plus_1_plus_1"],
            "always_runs_full_sequence": True,
            "model_selects_actions": False,
            "active_policy_claim_eligible": False,
            "factual_counterfactual_same_public_states_and_actions": True,
            "counterfactual_program_selection": (
                "lowest-program-id member of the initial four-rule version space "
                "whose partial-probe target differs from the factual target"
            ),
            "candidate_kind_used_by": "evaluator protocol construction only",
            "task_id_or_probe_id_passed_to_model": False,
        },
        "scope_and_privilege": {
            "mechanism_axes_given": ["collision", "trigger", "relation"],
            "mechanism_value_labels_used": False,
            "palette_role_canonicalization": True,
            "proposer_executor_kept_separate_from_active_verifier": True,
            "verifier_mode": args.verifier_mode,
            "frozen_executor_verifier": args.verifier_mode == "learned",
            "learned_population_search_interpretation_eligible": (
                args.verifier_mode == "learned" and verifier_audit["passed"]
            ),
            "symbolic_population_search_is_privileged_proposal_ceiling": (
                args.verifier_mode == "symbolic"
            ),
            "exact_version_space_used_by": "metrics and exact ceiling only",
            "true_program_used_by": "paired target construction and metrics only",
            "query_or_behavior_targets_passed_to_inference": False,
            "interpretation": (
                "Tests try-observe-refute/update under a fixed evidence schedule; "
                "it does not test learning an active query policy, discovering the "
                "privileged axes, or solving raw-pixel geometry."
            ),
        },
        "tasks": len(tasks),
        "context_split_kind": "latin_modulo_4_heldout",
        "context_fold": gram_fold,
        "paired_checkpoint_model_seed": gram_seed,
        "model_seed": args.seed,
        "data_master_seed": args.data_master_seed,
        "device": str(device),
        "torch_version": torch.__version__,
        "elapsed_seconds": round(elapsed, 6),
        "verifier_stage_audit": verifier_audit,
        "checkpoints": {
            "executor": {
                "path": str(executor_path),
                "sha256": _sha256_file(executor_path),
                "schema": checkpoints["executor_checkpoint"].get("checkpoint_schema_version"),
            },
            "active_verifier": {
                "path": str(active_verifier_path),
                "sha256": _sha256_file(active_verifier_path),
                "schema": checkpoints["active_verifier_checkpoint"].get(
                    "checkpoint_schema_version"
                ),
                "same_object_as_proposer_executor": (
                    active_verifier is proposer_executor
                ),
            },
            "gram": {
                "path": str(gram_path),
                "sha256": _sha256_file(gram_path),
                "schema": checkpoints["gram_checkpoint"].get("checkpoint_schema_version"),
            },
            "fixed_k4": {
                "path": str(fixed_path),
                "sha256": _sha256_file(fixed_path),
                "schema": checkpoints["fixed_checkpoint"].get("checkpoint_schema_version"),
            },
        },
        "source_sha256": _source_sha256(),
        "methods": methods,
    }
    _atomic_json(result_path, result)
    print(json.dumps(result, sort_keys=True, indent=2, allow_nan=False))


if __name__ == "__main__":
    main()
